version: '3.9'

services:

    stack_and_capital_handler:
      image: pysystem_image
      build:
        context: ./pysystemtrade
        dockerfile: ./Dockerfile
        args:
          GIT_TOKEN: ${GIT_TOKEN}
          SCRIPT_PATH: ${SCRIPT_PATH}
          ECHO_PATH: ${ECHO_PATH}
      container_name: stack_handler{NAME_SUFFIX}
      restart: on-failure
      environment:
        IPV4_NETWORK_PART: ${IPV4_NETWORK_PART}
        PYSYS_CODE: ${PYSYS_CODE}
      command: ["/bin/bash", "-c", "command_scripts/stack_and_capital_handler_container_commands.bash"]
      depends_on:
        - ib_gateway
        - mongo_db
      volumes:
        - ./echos:/home/echos
      networks:
        channel:
          ipv4_address: ${IPV4_NETWORK_PART}0.4
      stdin_open: true
      tty: true
      tini: true

    tester:
      image: pysystem_image
      container_name: price_update{NAME_SUFFIX}
      environment:
        IPV4_NETWORK_PART: ${IPV4_NETWORK_PART}
        PYSYS_CODE: ${PYSYS_CODE}
      command: ["/bin/sh", "-c", "cd sysproduction/linux/scripts && update_sampled_contracts"]
      depends_on:
        - ib_gateway
        - mongo_db
        - stack_and_capital_handler   # needed to avoid building same image twice
      volumes:
        - ./echos:/home/echos
      networks:
        channel:
          ipv4_address: ${IPV4_NETWORK_PART}0.7
      stdin_open: true
      tty: true
      tini: true

    daily_processes:
      image: pysystem_image
      container_name: system{NAME_SUFFIX}
      environment:
        IPV4_NETWORK_PART: ${IPV4_NETWORK_PART}
        PYSYS_CODE: ${PYSYS_CODE}
      command: ["/bin/sh", "-c", "command_scripts/daily_processes.bash"]
      depends_on:
        - ib_gateway
        - mongo_db
        - stack_and_capital_handler   # needed to avoid building same image twice
      volumes:
        - ./echos:/home/echos
        - ./reports:/home/reports
      networks:
        channel:
          ipv4_address: ${IPV4_NETWORK_PART}0.8
      stdin_open: true
      tty: true
      tini: true

    ib_gateway:
      build:
        context: ./ib_gateway
        dockerfile: ./Dockerfile
      container_name: ib_gateway${NAME_SUFFIX}
      restart: always
      ports:
        - "4002:4002"
        - "5900:5900"
      environment:
        TWSUSERID: ${TWSUSERID}
        TWSPASSWORD: ${TWSPASSWORD}
      networks:
        channel:
          ipv4_address: ${IPV4_NETWORK_PART}0.3

    mongo_db:
      container_name: mongo_db${NAME_SUFFIX}
      image: mongo
      restart: always
      volumes:
        - mongo_db:/data/db
        - mongo_conf:/data/configdb
      networks:
        channel:
          ipv4_address: ${IPV4_NETWORK_PART}0.2

    ipython:
      build:
        context: ./ipython
        dockerfile: ./Dockerfile
        args:
          GIT_TOKEN: add_personal_access_token_here
          ECHO_PATH: ${ECHO_PATH}
      container_name: ipython${NAME_SUFFIX}
      restart: always
      ports:
        - "8888:8888"
      networks:
        channel:
          ipv4_address: ${IPV4_NETWORK_PART}0.6
    
    db_backup:
      image: alpine
      volumes:
        - mongo_db:/data/db
        - mongo_conf:/data/configdb
        - ./db_backup:/backup
      command: sh -c "tar -cvf /backup/backup_db.tar /data/db; tar -cvf /backup/backup_conf.tar /data/configdb"
      tini: true

    db_restore:
      image: alpine    
      profiles: ["restore"]
      volumes:
        - mongo_db:/data/db
        - mongo_conf:/data/configdb
        - ./db_backup:/backup
      command: sh -c "cd /data/ && tar -xvf /backup/backup_db.tar --strip 1; cd /data/ && tar -xvf /backup/backup_conf.tar --strip 1"
      tini: true

volumes:
  mongo_db:
    name: mongo_db_volume${NAME_SUFFIX}
  mongo_conf:
    name: mongo_conf_volume${NAME_SUFFIX}

networks:
  channel:
    driver: bridge
    name: channel${NAME_SUFFIX}
    ipam:
      config:
        - subnet: ${IPV4_NETWORK_PART}0.0/16
          gateway: ${IPV4_NETWORK_PART}0.1


 # Backup concept; https://stackoverflow.com/a/56432886/1020693
 # about profile; https://docs.docker.com/compose/profiles/, https://stackoverflow.com/a/65957695/1020693

